_BASE_: maskformer_R50_bs32_60k.yaml
MODEL:
#  WEIGHTS: "/raid/huangsh/codes/MaskFormer/Backbone_weights/R-101.pkl"
  WEIGHTS: "/raid/huangsh/codes/Exps/MaskFormer/COCOStuff_R101_FAM/model_0059999.pth"
  RESNETS:
    DEPTH: 101
    STEM_TYPE: "basic"  # not used
    STEM_OUT_CHANNELS: 64
    STRIDE_IN_1X1: False
    OUT_FEATURES: ["res2", "res3", "res4", "res5"]
    # NORM: "SyncBN"
    RES5_MULTI_GRID: [1, 1, 1]  # not used

OUTPUT_DIR: "../Exps/MaskFormer/COCOStuff_R101_FAM"
#OUTPUT_DIR: "../Exps/MaskFormer/COCOStuff_R101_FPN"